#!/usr/bin/env python3
"""
Private Build Script for memopt

Creates a distributable wheel with source code protection.

Options:
1. Basic wheel (no compilation) - fast, some protection
2. Cython compiled wheel - slower build, better protection

Usage:
    python build_private.py          # Basic wheel
    python build_private.py --cython # Cython compiled wheel
"""

import os
import sys
import shutil
import subprocess
import argparse
from pathlib import Path


def clean_build_dirs():
    """Remove old build artifacts."""
    dirs_to_remove = ["build", "dist", "*.egg-info", "__pycache__"]
    for pattern in dirs_to_remove:
        for path in Path(".").glob(pattern):
            if path.is_dir():
                shutil.rmtree(path)
                print(f"Removed: {path}")


def build_basic_wheel():
    """Build a standard wheel (source included but not on PyPI)."""
    print("\n" + "=" * 60)
    print("Building Basic Wheel")
    print("=" * 60)

    # Build the wheel
    subprocess.run([sys.executable, "-m", "build", "--wheel"], check=True)

    # Find the built wheel
    wheels = list(Path("dist").glob("*.whl"))
    if wheels:
        print(f"\nWheel built: {wheels[0]}")
        print(f"Size: {wheels[0].stat().st_size / 1024:.1f} KB")
        return wheels[0]
    return None


def build_cython_wheel():
    """Build a Cython-compiled wheel (binary, no source)."""
    print("\n" + "=" * 60)
    print("Building Cython-Compiled Wheel")
    print("=" * 60)

    # Create setup_cython.py
    setup_cython = '''
import os
from setuptools import setup, find_packages
from Cython.Build import cythonize
from setuptools.extension import Extension

# Find all .py files to compile (excluding __init__.py)
py_files = []
for root, dirs, files in os.walk("memopt"):
    for f in files:
        if f.endswith(".py") and f != "__init__.py":
            filepath = os.path.join(root, f)
            # Convert path to module name
            module = filepath.replace("/", ".").replace("\\\\", ".")[:-3]
            py_files.append(Extension(module, [filepath]))

setup(
    name="memopt",
    version="0.4.0",
    packages=find_packages(),
    ext_modules=cythonize(
        py_files,
        compiler_directives={
            "language_level": "3",
            "boundscheck": False,
            "wraparound": False,
        },
        nthreads=4,
    ),
    install_requires=[
        "torch>=2.0.0",
        "numpy>=1.24.0",
    ],
    python_requires=">=3.8",
)
'''
    with open("setup_cython.py", "w") as f:
        f.write(setup_cython)

    try:
        # Build with Cython
        subprocess.run([
            sys.executable, "setup_cython.py",
            "build_ext", "--inplace"
        ], check=True)

        # Build wheel
        subprocess.run([
            sys.executable, "setup_cython.py",
            "bdist_wheel"
        ], check=True)

        wheels = list(Path("dist").glob("*.whl"))
        if wheels:
            print(f"\nCython wheel built: {wheels[0]}")
            return wheels[0]

    finally:
        # Cleanup
        if os.path.exists("setup_cython.py"):
            os.remove("setup_cython.py")
        # Remove .c files generated by Cython
        for c_file in Path(".").rglob("*.c"):
            c_file.unlink()

    return None


def create_install_instructions(wheel_path: Path):
    """Create installation instructions for customer."""
    instructions = f'''# memopt Installation Guide

## Requirements
- Python 3.8+
- CUDA-capable GPU
- PyTorch 2.0+

## Installation

```bash
# Install the wheel file
pip install {wheel_path.name}

# Verify installation
python -c "from memopt.profiler import api; print(api.__version__)"
```

## Quick Start

```python
import torch
from memopt.profiler import api

# Your model
model = YourModel().cuda()
sample = torch.randn(batch, seq, dim).cuda()

# Optimize
model, session = api.optimize(model, sample, verbose=True)
print(f"Speedup: {{session.total_speedup:.2f}}x")
```

## Support
Email: hello@memopt.ai

---
Version: 0.4.0
Build Date: {__import__("datetime").datetime.now().strftime("%Y-%m-%d")}
'''

    instructions_path = Path("dist") / "INSTALL.md"
    with open(instructions_path, "w") as f:
        f.write(instructions)
    print(f"Created: {instructions_path}")


def create_license_file():
    """Create proprietary license file."""
    license_text = '''MEMOPT PROPRIETARY LICENSE

Copyright (c) 2026 MemOpt Team. All rights reserved.

This software is provided to the licensee under a separate commercial
agreement. Unauthorized copying, modification, distribution, or use
of this software is strictly prohibited.

This software is provided "AS IS" without warranty of any kind.

For licensing inquiries: hello@memopt.ai
'''
    license_path = Path("dist") / "LICENSE"
    with open(license_path, "w") as f:
        f.write(license_text)
    print(f"Created: {license_path}")


def package_for_delivery(wheel_path: Path):
    """Create final delivery package."""
    import tarfile

    package_name = f"memopt-0.4.0-delivery"
    package_dir = Path("dist") / package_name

    # Create delivery directory
    package_dir.mkdir(exist_ok=True)

    # Copy wheel
    shutil.copy(wheel_path, package_dir)

    # Copy docs
    for doc in ["INSTALL.md", "LICENSE"]:
        src = Path("dist") / doc
        if src.exists():
            shutil.copy(src, package_dir)

    # Create tar.gz
    tar_path = Path("dist") / f"{package_name}.tar.gz"
    with tarfile.open(tar_path, "w:gz") as tar:
        tar.add(package_dir, arcname=package_name)

    print(f"\nDelivery package: {tar_path}")
    print(f"Size: {tar_path.stat().st_size / 1024:.1f} KB")

    # Cleanup
    shutil.rmtree(package_dir)

    return tar_path


def main():
    parser = argparse.ArgumentParser(description="Build memopt for private distribution")
    parser.add_argument("--cython", action="store_true", help="Build with Cython compilation")
    parser.add_argument("--clean", action="store_true", help="Clean build directories only")
    args = parser.parse_args()

    os.chdir(Path(__file__).parent)

    if args.clean:
        clean_build_dirs()
        print("Cleaned build directories")
        return

    print("=" * 60)
    print("MEMOPT PRIVATE BUILD")
    print("=" * 60)

    # Clean
    clean_build_dirs()

    # Build
    if args.cython:
        wheel_path = build_cython_wheel()
    else:
        wheel_path = build_basic_wheel()

    if not wheel_path:
        print("Build failed!")
        sys.exit(1)

    # Create supporting files
    Path("dist").mkdir(exist_ok=True)
    create_install_instructions(wheel_path)
    create_license_file()

    # Package for delivery
    delivery_path = package_for_delivery(wheel_path)

    print("\n" + "=" * 60)
    print("BUILD COMPLETE")
    print("=" * 60)
    print(f"\nDeliverable: {delivery_path}")
    print("\nTo deliver to customer:")
    print(f"  1. Upload {delivery_path} to secure location")
    print("  2. Send download link to customer")
    print("  3. Customer extracts and runs: pip install memopt-*.whl")


if __name__ == "__main__":
    main()
