apiVersion: v1
kind: Service
metadata:
  name: memopt-server
  namespace: {{ .Values.namespace }}
  labels:
    app: memopt-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: memopt-server
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
